use std::path::Path;
use std::process::Command;

use anyhow::{Context, Result, bail};
use tracing::{info, warn};

/// Create a branch, commit changes, push, and open a PR.
/// Returns the PR URL on success.
pub fn create_pr(
    repo_path: &Path,
    goal: &str,
    sub_tasks: &[(String, String, String)], // (description, model, status)
    quality_passed: bool,
    total_duration_ms: u64,
    tokens_in: u32,
    tokens_out: u32,
) -> Result<String> {
    let branch = branch_name(goal);

    // 1. Create and checkout branch
    info!(branch = %branch, "Creating branch");
    run_git(repo_path, &["checkout", "-b", &branch])?;

    // 2. Stage all changes
    run_git(repo_path, &["add", "-A"])?;

    // Check if there are changes to commit
    let status = Command::new("git")
        .args(["diff", "--cached", "--quiet"])
        .current_dir(repo_path)
        .status()
        .context("git diff failed")?;

    if status.success() {
        // No changes — switch back and clean up
        run_git(repo_path, &["checkout", "-"])?;
        run_git(repo_path, &["branch", "-D", &branch])?;
        bail!("No changes to commit");
    }

    // 3. Commit
    let commit_msg = build_commit_message(goal, sub_tasks, quality_passed, total_duration_ms);
    run_git(repo_path, &["commit", "-m", &commit_msg])?;
    info!("Changes committed");

    // 4. Push
    info!(branch = %branch, "Pushing branch");
    run_git(repo_path, &["push", "origin", &branch])?;

    // 5. Create PR via gh CLI
    let pr_body = build_pr_body(goal, sub_tasks, quality_passed, total_duration_ms, tokens_in, tokens_out);
    let pr_title = format!("agent: {}", truncate(goal, 70));

    info!("Creating PR via gh CLI");
    let output = Command::new("gh")
        .args(["pr", "create",
            "--title", &pr_title,
            "--body", &pr_body,
            "--head", &branch,
        ])
        .current_dir(repo_path)
        .output()
        .context("gh pr create failed — is gh installed and authenticated?")?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        warn!("gh pr create failed: {stderr}");
        // Still return the branch — the push succeeded
        bail!("PR creation failed: {stderr}");
    }

    let pr_url = String::from_utf8_lossy(&output.stdout).trim().to_string();
    info!(pr_url = %pr_url, "PR created");

    // 6. Switch back to default branch
    let _ = run_git(repo_path, &["checkout", "-"]);

    Ok(pr_url)
}

fn branch_name(goal: &str) -> String {
    let slug: String = goal
        .to_lowercase()
        .chars()
        .map(|c| if c.is_alphanumeric() || c == '-' { c } else { '-' })
        .collect();
    let slug = slug.trim_matches('-').to_string();
    // Collapse multiple hyphens
    let mut result = String::new();
    let mut last_hyphen = false;
    for c in slug.chars() {
        if c == '-' {
            if !last_hyphen { result.push(c); }
            last_hyphen = true;
        } else {
            result.push(c);
            last_hyphen = false;
        }
    }
    format!("agent/{}", truncate(&result, 50))
}

fn build_commit_message(
    goal: &str,
    sub_tasks: &[(String, String, String)],
    quality_passed: bool,
    duration_ms: u64,
) -> String {
    let mut msg = format!("agent: {}\n\nOrchestrated by alpha-swarm.\nSub-tasks: {} | Duration: {:.1}s\n",
        goal,
        sub_tasks.len(),
        duration_ms as f64 / 1000.0,
    );

    if !sub_tasks.is_empty() {
        msg.push_str("\nSub-tasks:\n");
        for (desc, model, status) in sub_tasks {
            msg.push_str(&format!("- {} ({}, {})\n", desc, model, status));
        }
    }

    msg.push_str(&format!("\nQuality gate: {}\n",
        if quality_passed { "passed" } else { "failed" }
    ));

    msg
}

fn build_pr_body(
    goal: &str,
    sub_tasks: &[(String, String, String)],
    quality_passed: bool,
    duration_ms: u64,
    tokens_in: u32,
    tokens_out: u32,
) -> String {
    let mut body = format!("## Goal\n{}\n\n", goal);

    if !sub_tasks.is_empty() {
        body.push_str("## Sub-tasks\n| # | Task | Model | Status |\n|---|------|-------|--------|\n");
        for (i, (desc, model, status)) in sub_tasks.iter().enumerate() {
            body.push_str(&format!("| {} | {} | {} | {} |\n", i + 1, desc, model, status));
        }
        body.push('\n');
    }

    body.push_str(&format!("## Quality Gate\n{}\n\n",
        if quality_passed { "All checks passed." } else { "Some checks failed." }
    ));

    body.push_str(&format!(
        "## Stats\n- Duration: {:.1}s\n- Tokens: {} in / {} out\n\n---\nGenerated by [alpha-swarm](https://github.com/alpha-swarm/alpha-swarm2)\n",
        duration_ms as f64 / 1000.0,
        tokens_in,
        tokens_out,
    ));

    body
}

/// Timeout for git operations (push can be slow over network)
#[allow(dead_code)]
const GIT_TIMEOUT_SECS: u64 = 60;

fn run_git(repo_path: &Path, args: &[&str]) -> Result<()> {
    let child = Command::new("git")
        .args(args)
        .current_dir(repo_path)
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .with_context(|| format!("git {} failed to start", args.join(" ")))?;

    let output = child.wait_with_output()
        .with_context(|| format!("git {} failed", args.join(" ")))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        bail!("git {} failed: {}", args.join(" "), stderr);
    }
    Ok(())
}

fn truncate(s: &str, max: usize) -> &str {
    if s.len() <= max { s } else { &s[..max] }
}
