use serde::{Deserialize, Serialize};

/// Embedding vector dimension. Single source of truth shared by the HNSW index
/// DDL and the startup dimension probe. Must match the output dimension of
/// `config.defaults.embed_model` (nomic-embed-text = 768).
pub const EMBED_DIM: usize = 768;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentRun {
    pub id: Option<String>,
    pub project: String,
    pub task_description: String,
    pub agent_id: String,
    pub model_used: String,
    pub status: RunStatus,
    pub files_modified: Vec<String>,
    pub diff: Option<String>,
    pub error_message: Option<String>,
    pub quality_gate_passed: Option<bool>,
    pub tokens_input: u32,
    pub tokens_output: u32,
    pub duration_ms: u64,
    pub created_at: String,
    pub embedding: Option<Vec<f32>>,
    // Conversation tracking
    #[serde(default)]
    pub prompt_sent: Option<String>,
    #[serde(default)]
    pub response_text: Option<String>,
    #[serde(default)]
    pub attempts: Vec<AttemptRecord>,
    #[serde(default)]
    pub started_at: Option<String>,
    #[serde(default)]
    pub last_activity_at: Option<String>,
    #[serde(default)]
    pub parent_run_id: Option<String>,
    #[serde(default)]
    pub progress_message: Option<String>,
    #[serde(default)]
    pub tool_calls: Vec<ToolCallRecord>,
    /// Phase timing breakdown (embedding_ms, rag_ms, planning_ms, agent_ms, qg_ms).
    #[serde(default)]
    pub phase_timings: Option<PhaseTimingRecord>,
}

/// Timing breakdown for each phase of a swarm run.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PhaseTimingRecord {
    pub embedding_ms: u64,
    pub rag_ms: u64,
    pub planning_ms: u64,
    pub agent_execution_ms: u64,
    pub quality_gate_ms: u64,
}

/// Record of a tool call made during agent execution.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCallRecord {
    pub tool: String,
    pub params_preview: String,
    pub result_preview: String,
    pub is_error: bool,
    pub duration_ms: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttemptRecord {
    pub attempt: u32,
    pub model: String,
    pub prompt_preview: String,
    pub response_preview: String,
    pub tokens_input: u32,
    pub tokens_output: u32,
    pub duration_ms: u64,
    pub quality_passed: Option<bool>,
    pub error: Option<String>,
    pub timestamp: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum RunStatus {
    Pending,
    Planning,
    Planned,
    Approved,
    Running,
    Passed,
    Failed,
    Skipped,
}

/// A plan generated by the orchestrator for user review before execution.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GoalPlan {
    #[serde(default)]
    pub id: Option<String>,
    pub run_id: String,
    pub project: String,
    pub goal: String,
    pub version: u32,
    pub sub_tasks: Vec<PlannedTask>,
    pub model_used: String,
    pub tokens_input: u32,
    pub tokens_output: u32,
    pub duration_ms: u64,
    #[serde(default)]
    pub user_feedback: Option<String>,
    pub status: String,
    pub context_files: Vec<String>,
    #[serde(default)]
    pub web_searches: Vec<String>,
    pub reasoning: String,
    pub created_at: String,
    /// Memory pattern ids injected into this plan's prompt (SONA signal).
    #[serde(default)]
    pub retrieved_pattern_ids: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlannedTask {
    pub id: String,
    pub description: String,
    pub files: Vec<String>,
    pub complexity: String,
    pub rationale: String,
    /// Task ids this task depends on (DAG edges). Persisted so the plan's
    /// dependency graph survives the SubTask → PlannedTask projection.
    #[serde(default)]
    pub depends_on: Vec<String>,
    /// Graph template ("edit", "create", "refactor", "doc") if assigned by the planner.
    #[serde(default)]
    pub template: Option<String>,
    /// Direct edit payload if the planner emitted one (mirror of orchestrator's DirectEdit;
    /// knowledge-base cannot depend on orchestrator, so the shape is duplicated here).
    #[serde(default)]
    pub edit: Option<PlannedEdit>,
}

/// WASI-portable mirror of `swarm_orchestrator::DirectEdit`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlannedEdit {
    pub path: String,
    pub old: String,
    pub new: String,
}

// --- Agent memory (namespaced semantic memory; SONA learning loop) ---

/// Distilled goal→plan patterns from successful runs.
pub const MEM_NS_PATTERNS: &str = "patterns";
/// Concrete working solutions worth recalling verbatim.
pub const MEM_NS_SOLUTIONS: &str = "solutions";
/// User feedback on plans, keyed by goal shape.
pub const MEM_NS_FEEDBACK: &str = "feedback";
/// Error signatures from failed runs.
pub const MEM_NS_ERRORS: &str = "errors";
/// Full run trajectories (goal → steps → outcome).
pub const MEM_NS_TRAJECTORIES: &str = "trajectories";

/// One namespaced memory entry. `embedding` is skipped in bridge JSON when
/// empty so list/search responses stay small.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemoryEntry {
    #[serde(default)]
    pub id: Option<String>,
    pub namespace: String,
    /// Stable key within (namespace, project) — e.g. a goal-shape hash.
    pub key: String,
    pub content: String,
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub embedding: Vec<f32>,
    #[serde(default)]
    pub metadata: serde_json::Value,
    pub project: String,
    pub created_at: String,
    pub last_used_at: String,
    pub use_count: u32,
    #[serde(default)]
    pub ttl_secs: Option<u64>,
}

/// A semantic search hit with its cosine similarity.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemorySearchHit {
    pub entry: MemoryEntry,
    pub similarity: f32,
}

impl AgentRun {
    pub fn new(
        project: impl Into<String>,
        task_description: impl Into<String>,
        agent_id: impl Into<String>,
        model_used: impl Into<String>,
    ) -> Self {
        Self {
            id: None,
            project: project.into(),
            task_description: task_description.into(),
            agent_id: agent_id.into(),
            model_used: model_used.into(),
            status: RunStatus::Running,
            files_modified: Vec::new(),
            diff: None,
            error_message: None,
            quality_gate_passed: None,
            tokens_input: 0,
            tokens_output: 0,
            duration_ms: 0,
            #[cfg(feature = "native")]
            created_at: chrono::Utc::now().to_rfc3339(),
            #[cfg(not(feature = "native"))]
            created_at: String::new(),
            embedding: None,
            prompt_sent: None,
            response_text: None,
            attempts: Vec::new(),
            started_at: None,
            last_activity_at: None,
            parent_run_id: None,
            progress_message: None,
            tool_calls: Vec::new(),
            phase_timings: None,
        }
    }
}
