package alpha-swarm:api-server@0.1.0;

world api-server {
    import wasi:http/outgoing-handler@0.2.0;
    import wasi:http/types@0.2.0;
    import wasi:clocks/wall-clock@0.2.0;
    import wasi:clocks/monotonic-clock@0.2.0;
    import wasi:io/streams@0.2.0;
    import wasi:io/poll@0.2.0;
    import wasi:io/error@0.2.0;
    import wasmcloud:messaging/consumer@0.2.0;

    export wasi:http/incoming-handler@0.2.0;
}
